function(configure_ditests_lit_site_cfg input output)
  set(LIT_SITE_CFG_IN_HEADER
      "## Autogenerated for ditests from ${input}\n## Do not edit!"
  )
  
  set(DITESTS_PROJECT_DIR ${PROJECT_SOURCE_DIR})
  set(DITESTS_BUILD_DIR ${CMAKE_BINARY_DIR})

  file(READ ${input} contents)
  string(CONFIGURE "${contents}" contents @ONLY)
  file(GENERATE
    OUTPUT
      ${output}
    CONTENT
      "${contents}"
    FILE_PERMISSIONS
      OWNER_READ OWNER_WRITE OWNER_EXECUTE
      GROUP_READ
      WORLD_READ
  )
endfunction()
